source 'https://github.com/CocoaPods/Specs'
workspace 'GfycatBrowser.xcworkspace'

platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'GfycatBrowser' do
    project 'GfycatBrowser.xcodeproj'
    pod 'GfycatKit'
end

